phpbr_app_cole:
    resource: "@PhpbrAppBundle/Resources/config/routing/cole.yml"

phpbr_app_url:
    resource: "@PhpbrAppBundle/Resources/config/routing/url.yml"
    prefix:   /url

phpbr_app_main:
    resource: "@PhpbrAppBundle/Resources/config/routing/main.yml"

phpbr_app_fos:
    resource: "@PhpbrAppBundle/Resources/config/routing/fos.yml"

phpbr_app_artigo:
    resource: "@PhpbrAppBundle/Resources/config/routing/artigo.yml"
    prefix: /artigos/

phpbr_app_meus_artigos:
    resource: "@PhpbrAppBundle/Resources/config/routing/meusartigos.yml"
    prefix: /meus-artigos/

phpbr_app_forum:
    resource: "@PhpbrAppBundle/Resources/config/routing/forum.yml"
    prefix: /forum


