parameters:
    my_user_provider.class: Phpbr\Bundle\AppBundle\Security\Core\User\FOSUBUserProvider
    gravatar.class: Phpbr\Bundle\AppBundle\Gravatar
    gravatar.twig_extension.class: Phpbr\Bundle\AppBundle\Twig\GravatarExtension
    tempo_passado.twig_extension.class: Phpbr\Bundle\AppBundle\Twig\TempoExtension
    forum_topico.twig_extension.class: Phpbr\Bundle\AppBundle\Twig\ForumTopicoExtension
    forum_mensagem.twig_extension.class: Phpbr\Bundle\AppBundle\Twig\ForumMensagemExtension
    forum_categoria.twig_extension.class: Phpbr\Bundle\AppBundle\Twig\ForumCategoriaExtension
    phpbr.coleservice.em.class: Phpbr\Bundle\AppBundle\Services\ColeService

services:
    my_user_provider:
        class: "%my_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        # arguments: [@fos_user.user_manager,{facebook: facebook_id, google: google_id}]
        arguments: [@fos_user.user_manager,{facebook: facebook_id }]

    phpbr_app.registration.form.type:
        class: Phpbr\Bundle\AppBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: phpbr_user_registration }

    phpbr_app.profile.form.type:
        class: Phpbr\Bundle\AppBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: phpbr_user_profile }

    gravatar:
        class: "%gravatar.class%"

    gravatar.twig_extension:
        class: "%gravatar.twig_extension.class%"
        public: false
        tags:
            - { name: twig.extension }

    forum_topico.twig_extension:
        class: "%forum_topico.twig_extension.class%"
        public: false
        arguments:
            em: 
                "@doctrine.orm.entity_manager"
        tags:
            - { name: twig.extension }

    forum_mensagem.twig_extension:
        class: "%forum_mensagem.twig_extension.class%"
        public: false
        arguments:
            em: 
                "@doctrine.orm.entity_manager"
        tags:
            - { name: twig.extension }

    forum_categoria.twig_extension:
        class: "%forum_categoria.twig_extension.class%"
        public: false
        arguments:
            em:
                "@doctrine.orm.entity_manager"
        tags:
            - { name: twig.extension }

    tempo_passado.twig_extension:
        class: "%tempo_passado.twig_extension.class%"
        public: false
        tags:
            - { name: twig.extension }

    pagerfanta.view.phpbr:
        class: Phpbr\Bundle\AppBundle\Pagerfanta\CustomView
        public: false
        arguments:
            - @translator.default
        tags: [{ name: pagerfanta.view, alias: phpbr }]

    phpbr_cole_service_em:
        class: "%phpbr.coleservice.em.class%"
        arguments:
            entityManager: "@doctrine.orm.entity_manager"

