parameters:
    my_user_provider.class: Phpbr\AppBundle\Security\Core\User\FOSUBUserProvider
    gravatar.class: Phpbr\AppBundle\Utils\Gravatar
    gravatar.twig_extension.class: Phpbr\AppBundle\Twig\GravatarExtension
    tempo_passado.twig_extension.class: Phpbr\AppBundle\Twig\TempoExtension
    forum_topico.twig_extension.class: Phpbr\AppBundle\Twig\ForumTopicoExtension
    forum_mensagem.twig_extension.class: Phpbr\AppBundle\Twig\ForumMensagemExtension
    forum_categoria.twig_extension.class: Phpbr\AppBundle\Twig\ForumCategoriaExtension
    forum_conta_mensagens.twig_extension.class: Phpbr\AppBundle\Twig\ForumContaMensagensExtension
    phpbr.coleservice.em.class: Phpbr\AppBundle\Services\ColeService
    phpbr.artigoservice.em.class: Phpbr\AppBundle\Services\ArtigoService
    phpbr.artigoapiservice.em.class: Phpbr\AppBundle\Services\ArtigoApiService
    phpbr.defaultservice.em.class: Phpbr\AppBundle\Services\DefaultService
    phpbr.eventservice.em.class: Phpbr\AppBundle\Services\EventService
    phpbr.urlservice.em.class: Phpbr\AppBundle\Services\UrlService
    phpbr.ircapiservice.em.class: Phpbr\AppBundle\Services\IrcApiService


services:
    my_user_provider:
        class: "%my_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        # arguments: [@fos_user.user_manager,{facebook: facebook_id, google: google_id}]
        arguments: [@fos_user.user_manager,{facebook: facebook_id }]

    phpbr_app.registration.form.type:
        class: Phpbr\AppBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: phpbr_user_registration }

    phpbr_app.profile.form.type:
        class: Phpbr\AppBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: phpbr_user_profile }

    gravatar:
        class: "%gravatar.class%"

    gravatar.twig_extension:
        class: "%gravatar.twig_extension.class%"
        public: false
        tags:
            - { name: twig.extension }

    forum_topico.twig_extension:
        class: "%forum_topico.twig_extension.class%"
        public: false
        arguments:
            em: 
                "@doctrine.orm.entity_manager"
        tags:
            - { name: twig.extension }

    forum_mensagem.twig_extension:
        class: "%forum_mensagem.twig_extension.class%"
        public: false
        arguments:
            em: 
                "@doctrine.orm.entity_manager"
        tags:
            - { name: twig.extension }


    forum_conta_mensagens.twig_extension:
        class: "%forum_conta_mensagens.twig_extension.class%"
        public: false
        arguments:
            em: 
                "@doctrine.orm.entity_manager"
        tags:
            - { name: twig.extension }


    forum_categoria.twig_extension:
        class: "%forum_categoria.twig_extension.class%"
        public: false
        arguments:
            em:
                "@doctrine.orm.entity_manager"
        tags:
            - { name: twig.extension }

    tempo_passado.twig_extension:
        class: "%tempo_passado.twig_extension.class%"
        public: false
        tags:
            - { name: twig.extension }

    pagerfanta.view.phpbr:
        class: Phpbr\AppBundle\Pagerfanta\CustomView
        public: false
        arguments:
            - @translator.default
        tags: [{ name: pagerfanta.view, alias: phpbr }]

    phpbr_cole_service_em:
        class: "%phpbr.coleservice.em.class%"
        arguments:
            entityManager: "@doctrine.orm.entity_manager"

    phpbr_artigo_service_em:
        class: "%phpbr.artigoservice.em.class%"
        arguments:
            entityManager: "@doctrine.orm.entity_manager"

    phpbr_artigo_api_service_em:
        class: "%phpbr.artigoapiservice.em.class%"
        arguments:
            entityManager: "@doctrine.orm.entity_manager"

    phpbr_default_service_em:
        class: "%phpbr.defaultservice.em.class%"
        arguments:
            entityManager: "@doctrine.orm.entity_manager"

    phpbr_event_service_em:
          class: "%phpbr.eventservice.em.class%"
          arguments:
              entityManager: "@doctrine.orm.entity_manager"

    phpbr_url_service_em:
        class: "%phpbr.urlservice.em.class%"
        arguments:
            entityManager: "@doctrine.orm.entity_manager"

    phpbr_ircapi_service_em:
        class: "%phpbr.ircapiservice.em.class%"
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
