Phpbr\Bundle\AppBundle\Entity\Forum\Topico:
    type: entity
    table: forum_topico
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        assunto:
            type: string
            length: 255
        mensagem:
            type: text
        dataCriacao:
            type: datetime
        slug:
            type: string
            length: 255
            gedmo:
                slug:
                    separator: -
                    fields:
                        - id
                        - assunto
    manyToOne:
        categoria:
            targetEntity: Phpbr\Bundle\AppBundle\Entity\Forum\Categoria
            inversedBy: topico
            joinColumn:
                name: categoria_id
                referencedColumnName: id
                onDelete: CASCADE
        user:
            targetEntity: Phpbr\Bundle\AppBundle\Entity\User
            inversedBy: topico
            joinColumn:
                name: user_id
                referencedColumnName: id
                onDelete: CASCADE
    lifecycleCallbacks: {  }

    oneToMany:
        mensagens:
            targetEntity: Phpbr\Bundle\AppBundle\Entity\Forum\Mensagem
            mappedBy: topico
