phpbr_api_get_artigo:
    path: /v1/artigo/{id}
    defaults: { _controller: "PhpbrAppBundle:ArtigoApi:getArtigo" }
    requirements:
        _method: GET
        id: "\d+"
    host: %website%


phpbr_api_put_irc:
    path: /v1/irc/{api_key}/{nicks}
    defaults: { _controller: "PhpbrAppBundle:IrcApi:putIrc" }
    requirements:
        _method: PUT
    host: %website%


phpbr_api_get_irc:
    path: /v1/irc
    defaults: { _controller: "PhpbrAppBundle:IrcApi:getNicks" }
    requirements:
        _method: GET
    host: %website%



